# **Netflix Dataset Overview**
## **Project Objective**

**The objective of this project is to perform exploratory data analysis (EDA) on Netflix Movies and TV Shows data to identify content distribution patterns, genre trends, country-wise contributions, rating distributions, and growth of Netflix content over time.**

**Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Load Dataset**

In [1]:
df = pd.read_csv(r"C:\Users\fidha\Downloads\archive (21)\netflix_titles.csv.zip")

NameError: name 'pd' is not defined

**First 5 Rows Of Dataset**

In [5]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

**Dataset Shape**

In [6]:
df.shape

(8807, 12)

**Columns Names**

In [8]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

**DataSet Information**

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

**Statistical Summary**

In [11]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

**Unique Values Per Columns**

In [12]:
df.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

**Numerical columns**

In [19]:
num_cols = df.select_dtypes(include="number").columns
num_cols

Index(['release_year'], dtype='str')

**Categorical Columns**

In [17]:
cat_cols = df.select_dtypes(include=["object", "string"]).columns
cat_cols

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

**Convert Date Columns**

In [21]:
df["date_added"] = pd.to_datetime(df["date_added"], errors='coerce')

**Date columns**

In [22]:
date_cols = df.select_dtypes(include="datetime").columns
date_cols

Index(['date_added'], dtype='str')

**Missing Value Analysis**

In [23]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        98
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

**Duplicate Rows**

In [24]:
df.duplicated().sum()

np.int64(0)

**Check Logical Bounds & Outliers**

In [25]:
print("\n Release Year Distribution")
print(df["release_year"].describe())

 Release Year Distribution
count    8807.000000
mean     2014.180198
std         8.819312
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

**Check for any invalid future release years**

In [26]:
invalid_years = df[df["release_year"] > 2026]
print(f"Rows with invalid future release years: {len(invalid_years)}")

Rows with invalid future release years: 0

**Data Quality Issue Log**




## Data Quality Issues 
|Issue  | Column |	Observation |
|-------|---------|-------------|
|Missing Values |	director/cast/country/date_added/rating |Null values detected in multiple text columns
|Duplicates	|Entire Dataset	|Check required for duplicate show_id entries
|Mixed Formats	|duration	|Contains mixed measurement strings ('Seasons' vs 'min')
|Datatype Issues	|date_added	|Needs conversion from string object to datetime
|Incomplete Data|	rating / duration	|Empty or misaligned categories present


**Initial Observations**

# Initial Observations

- Dataset contains a mix of categorical text features and numeric/temporal variables
- The 'date_added' column contains object text strings requiring conversion to datetime formats
- Missing values are present across several core columns such as 'director', 'cast', and 'country'
- Categorical distributions show heavy representation from 'United States' and 'TV-MA' ratings
- The 'duration' feature uses mixed metric terminology requiring parsing ('Seasons' vs. 'min')
- Dataset is highly suitable for advanced EDA, content recommendations, and text-based analytics